### ISSUE TITLE
Property assignment not supported in Interface operations

### ISSUE THREAD

**Issue by pmjordan** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#42]
Consider this template
``` yaml
tosca_definitions_version: tosca_simple_yaml_1_3

metadata:

  template_name: Interfaces Example
  template_author: Puccini

node_types:

  # (You can also define interfaces in group and relationship types)

  Server:
    derived_from: tosca:Compute
    interfaces:
      Maintenance:
        type: Maintenance

      # All normative node types (derived from Root) have the "Standard" lifecycle interface
      Standard:
        # (You can override the type here, but only if it's a derived type)
        # You can define operations both at the interface type and at the node type 
        operations:
          create:
            # You *must* define inputs in order to assign them at the template
            inputs:
              retries:
                type: integer
    attributes:
      progress:
        type: string
      last_turned_off:
        type: timestamp

  BetterServer:
    derived_from: Server
    interfaces:
      Standard:
        operations:
          create:
            inputs:
              # Inputs are inherited (both from interface type and node type)
              retries: 3

data_types:

  Retries:
    derived_from: integer
    constraints:
    - greater_or_equal: 0

interface_types:

  Maintenance:
    # You can define inputs for the interface as a whole as well as for individual operations
    inputs:
      mode:
        type: string
        constraints:
        - valid_values: [ staging, production ]
    operations:
      maintenance_on:
        description: Turn maintenance mode on
      maintenance_off:
        description: Turn maintenance mode off
        inputs:
          priority:
            type: float
        outputs:
          # Outputs map to *attributes*
          # The attribute must be declared at the type
          timestamp: [ SELF, last_turned_off ]
    notifications:
      progress:
        description: Progress on maintenance mode
        outputs:
          percentage: [ SELF, progress ]

topology_template:

  node_templates:

    server:
      type: Server
      interfaces:
        Standard:
          operations:
            # Shortest notation has just the implementation
            start: /opt/scripts/start.sh
            stop: /opt/scripts/start.sh

            # Longer notation with inputs
            create:
              implementation: scripts/create.sh
              inputs:
                retries: 3

            # Longest notation also allows adding dependencies and other params to the implementation
            configure:
              implementation:
                primary: /opt/scripts/configure.sh
                dependencies:
                - /opt/scripts/utils.sh
                - /opt/scripts/config.yaml
                timeout: 3
                operation_host: SELF

        Maintenance:
          inputs:
            mode: production
          operations:
            maintenance_on: /opt/scripts/maintenance_on.sh
            maintenance_off:
              implementation: /opt/scripts/maintenance_off.sh
              inputs:
                priority: .75
          notifications:
            progress: /opt/scripts/progress.sh
``` 
This fails validation with the message
``
[ERROR] interfaces.yaml:node_types:BetterServer:interfaces:Standard:operations:create: - {'inputs': {'retries': 3}} is not valid under any of the given schemas!
``
This is an example of property assignment within an interface operation. This seems to be allowed by 3.6.17.2.3. of the 1.3 spec.

FYI. I have submitted a similar [issue to puccini](https://github.com/tliron/puccini/issues/99)

**Comment by philippemerle** [comment]
Hi @pmjordan, thanks you for reporting this issue.

> This is an example of property assignment within an interface operation. This seems to be allowed by 3.6.17.2.3. of the 1.3 spec.

Section 3.6.17.2.3 is related to _Extended notation for use in **Template definitions**_ and not in type definitions (the previous section in the spec). Property assignment is not allowed in type definition.

Replace
```yaml
              retries: 3
```
by
```yaml
              retries:
                value: 3
```

Unfortunalety other errors will appear
```
[ERROR] issues/issue_42.yaml@77,25:interface_types:Maintenance:notifications:progress:outputs:percentage: ['SELF', 'progress'] - SELF undefined!
[Warning] issues/issue_42.yaml@104,19:topology_template:node_templates:server:interfaces:Standard:operations:configure:implementation:dependencies[1]: /opt/scripts/config.yaml - no artifact type found!
[ERROR] issues/issue_42.yaml@106,33:topology_template:node_templates:server:interfaces:Standard:operations:configure:implementation:operation_host: SELF - currently unchecked!
[ERROR] issues/issue_42.yaml@118,13:topology_template:node_templates:server:interfaces:Maintenance:notifications: {'progress': '/opt/scripts/progress.sh'} - currently unchecked!
```

I will implement these checkings asap.

**Comment by philippemerle** [comment]
Notifications are very underspecified and under illustrated in TOSCA v1.3. There is just one concrete example in section 2.17! For information, TOSCA v2.0 better specifies notifications. So, following is my own (perhaps incorrect) interpretation.

Your following fragment
```yaml
interface_types:
  Maintenance:
    # omitted here for brevity
    notifications:
      progress:
        description: Progress on maintenance mode
        outputs:
          percentage: [ SELF, progress ]
```
uses the grammar defined in Section 3.6.19.2 of TOSCA v1.3. But this section states "_The following multi-line grammar may be used in Node or Relationship Template or Type definitions_". I interpret this as can *only* be used in, i.e. can not be used in other places like Interface Type definitions.

Moreover, `progress` refers to an attribute, but attributes can not be defined in interface types, so when static type checking the `Maintenance` interface type the parser does not know in which node types the interface will be used.

So you should revisite your example like this
```
tosca_definitions_version: tosca_simple_yaml_1_3
...
node_types:
...
  Server:
    derived_from: tosca:Compute
    interfaces:
      Maintenance:
        type: Maintenance
        notifications: # added
          progress:
            outputs:
              percentage: [ SELF, progress ] #  here progress is an attribute of Server
          # this looks like example in section 2.17. 
...
interface_types:
  Maintenance:
...
    notifications:
      progress:
        description: Progress on maintenance mode
        # outputs not specified here but mapped in node types.
...
```
