### ISSUE TITLE
unassigned relationship properties

### ISSUE THREAD

**Issue by philippemerle** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#52]
In the following service template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    compute:
      type: tosca.nodes.Compute
      requirements:
        - local_storage: storage
    storage:
      type: tosca.nodes.Storage.BlockStorage
      properties:
        name: storage
```
the location property of the relationship of the local_storage requirement must be assigned as this property is required.
