### ISSUE TITLE
get_attribute with a requirement as parameter

### ISSUE THREAD

**Issue by philippemerle** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#56]
Parsing the following service template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    compute:
      type: tosca.nodes.Compute
      capabilities:
        host:
          properties:
            name: mycompute
    software:
      type: tosca.nodes.SoftwareComponent
      requirements:
        - host: compute
      interfaces:
        Standard:
          operations:
            configure:
              inputs:
                property_host_name:  { get_property: [ SELF, host, name ]}
                attribute_host_name: { get_attribute: [ SELF, host, name ]}
```
produces an error
```
[ERROR] issue.yaml@21,38:topology_template:node_templates:software:interfaces:Standard:operations:configure:inputs:attribute_host_name: {'get_attribute': ['SELF', 'host', 'name']} - host attribute undefined!
```

As `get_property: [ SELF, host, name ]` is considered as a correct expression, then `get_attribute: [ SELF, host, name ]` shall be considered as a correct expression.
